;; DO NOT EDIT THIS FILE DIRECTLY
;; It is generated from an Org file.
;;
;; You should make any changes there and regenerate it with C-c C-v t

;; (menu-bar-mode 1)
(tool-bar-mode -1)
(tab-line-mode -1)
;; (scroll-bar-mode 1)

(setq inhibit-startup-message t)

(when (fboundp 'toggle-frame-maximized)
  (toggle-frame-maximized))

(setq site-run-file nil)

(setq gc-cons-threshold 8000000) ;; 8 MB
