* My Emacs config

In March 2021 I collected all my Emacs config files into one: [[https://github.com/wdenton/.emacs.d/blob/master/init.org][init.org]].  Now everything is in one big [[https://orgmode.org/][Org]] file, with lots of comments (and more to come), and whenever I make a change I run =Ctrl-c Ctrl-v t= to [[https://orgmode.org/manual/Extracting-Source-Code.html][tangle]] all the code into two Emacs Lisp files.

If, for some reason I cannot fathom, you want to try out my Emacs configuration, run these commands. First you'll move your existing Emacs configuration out of the way, then you'll clone mine.

#+begin_src shell :eval no
cd ~
mv .emacs .emacs.BAK
mv .emacs.d .emacs.d.BAK
git clone https://github.com/wdenton/.emacs.d.git
emacs
#+end_src

When you run Emacs it will probably spend a while downloading and installing packages. It may complain some are missing.  That's all right. When it's done, close it (=Ctrl-x Ctrl-c=) and then restart.  You'll be left with an Emacs that runs just like mine.

=M-x all-praise-emacs=

* License

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.

Copyright 2012–2021 William Denton <wtd@pobox.com>.
